### ISSUE TITLE
Improve experience setting this extension with StarCoder model 

### ISSUE THREAD

**Issue by abidlabs** [bigcode-project/jupytercoder#18]
A small point, but it was tricky for me to set this up because I had to copy paste two different things: the URL and the API key into the extension:

<img width="290" alt="image" src="https://user-images.githubusercontent.com/1778297/236584102-83f6a889-bf3f-458c-b671-e4570d032056.png">

But every time I would paste one and focus out to the webpage to the copy the other, the pop window would disappear. If possible, please persist the pop up window. If not, at least please persist the contents that have been copy-pasted there.

**Comment by liyongsea** [comment]
Working on it !

**Comment by liyongsea** [comment]
As a temporary solution we will start by just making the bigcode url pre filled (https://api-inference.huggingface.co/models/bigcode/starcoderbase/)
Please share your suggestion on how to improve the UI !

**Comment by liyongsea** [comment]
partially solved by https://github.com/bigcode-project/jupytercoder/pull/21
we might want to create a real config page later

**Comment by abidlabs** [comment]
Thanks, I think this makes sense for now. Having whatever is copied persist instead of having to click Save could be another option.

**Comment by liyongsea** [comment]
I thought it might imply auto save which might create other issue. But you are right. Let's see if it is faisible
