### ISSUE TITLE
Bug fix mode

### ISSUE THREAD

**Issue by liyongsea** [bigcode-project/jupytercoder#2]
Use the following prompt to fix bug
<commit_before>code<commit_msg>fix bug, error_message: ... <commit_after>code<|endoftext|>
![image](https://user-images.githubusercontent.com/6381544/233831634-83d1fda1-473c-4600-86e1-10550ac4ff6f.png)

**Comment by Wzixiao** [comment]
https://github.com/bigcode-project/jupytercoder/pull/33
